### PR TITLE
WeatherHandler編寫.java

### PR DESCRIPTION
**Pull request by markhsumark**
add WeatherHandler.java in path src/main/java/handler
add org.json dependency in build.gradle

### CODE REVIEW

**Comment by asas1asas200** [comment]
Dotfiles(e.g. .classpath, .project) shouldn't be committed because it just related to your customized settings.

**Review by asas1asas200 — CHANGES_REQUESTED** [review]
1. Remove the dotfiles.
2. Store token as a file if you can.

**Comment by asas1asas200** [comment]
You can try to add your handler into the ```run()``` function in CLI to test if it works correctly.

**Comment by markhsumark** [comment]
更新WeatherHandler 針對current_weather的搜尋更精準
加入兩個csv檔到tokens裡（內有天氣url、授權碼）

**Pull request merged**
